 	<?php
	include_once("../model/mod.login.php");
	include_once("../model/mod.user.php");
	include_once("../lib/ini.dbstring.php");
	include_once ("../lib/ini.functions.php");
	include_once ("../Classes/PHPExcel/IOFactory.php");
    ob_start();
    sec_session_start();
  // Import and insert
if (isset($_POST['cmd']) && $_POST['cmd'] == "import") {

	// Store variables
	$inputFileName = $_FILES['uploadFile']['tmp_name'];
	$op_file_type = $_FILES['uploadFile']['type'];
	$array = Array();

	// Clear session first
	$_SESSION['cmd'] = "";	
	$_SESSION['cmd']['err']="";

	// Validate
	($inputFileName == "" || $op_file_type != "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet") ? $_SESSION['cmd']['err']['op_filename'] = 1 : $_SESSION['cmd']['data']['op_filename'] = $inputFileName;

	// Has errors and redirect with errors
	if (!empty($_SESSION['cmd']['err'])) {
	
		$_SESSION['cmd']['err']="error";
		header("location: ../admin/user_import.php");
		exit;
	}

	try {
	
	
		$inputFileType = PHPExcel_IOFactory::identify($inputFileName);
		$objReader = PHPExcel_IOFactory::createReader($inputFileType);
		$objPHPExcel = $objReader -> load($inputFileName);
		$objReader -> setReadDataOnly(true);
	} catch(Exception $e) {


		die('Error loading file "' . pathinfo($inputFileName, PATHINFO_BASENAME) . '": ' . $e -> getMessage());
	}

	$objWorkSheet = $objPHPExcel -> getActiveSheet();
	
	// Get autogenerated code
	//$code = code(3, $db);
	
	$result = $db -> query("SELECT user_id FROM `user` ORDER BY user_id DESC limit 1");
	$rowcount = $result -> num_rows;

	if ($rowcount == "") {
	
		$last_id = 0;
	} else {
		
		while ($row = $result -> fetch_array(MYSQLI_NUM)) {
			$last_id = $row[0];
		}
	}
	// Iterate through rows
	foreach ($objWorkSheet->getRowIterator() as $row) {
		$cellIterator = $row -> getCellIterator();
		$cellIterator -> setIterateOnlyExistingCells(false);
		$rowIndex = $row -> getRowIndex();
		
		// Skip first row of titles
		if($rowIndex == 1) {
	
		continue;
		}
		
		//$rowIndex = $rowIndex - 1;
		$rowIndex = $rowIndex -2;
		
		$i = $last_id++ + 1;
		$b = str_pad($i, 4, '0', STR_PAD_LEFT);
		
		// Iterate through cells
		foreach ($cellIterator as $cell) {
		
			// Break the loop if cell is Empty or Null
			if (is_null($cell -> getCalculatedValue())) {
				break;
			}
			if ('A' == $cell -> getColumn()) {
				$array[$rowIndex]['user_name'] = $cell -> getCalculatedValue();
			} else if ('B' == $cell -> getColumn()) {
				$array[$rowIndex]['user_eid'] = $cell -> getCalculatedValue();
			} else if ('C' == $cell -> getColumn()) {
				$array[$rowIndex]['user_password'] = $cell -> getCalculatedValue();
				$password = $array[$rowIndex]['user_password'];
				$password = hash("sha256", $password);
				define("MAX_LENGTH", 6);
				$intermediateSalt = md5(uniqid(rand(), true));
				$salt = substr($intermediateSalt, 0, MAX_LENGTH);
				$user_password = hash("sha256", $password . $salt);
				$array[$rowIndex]['user_password']=$user_password;
			} else if ('D' == $cell -> getColumn()) {		
				$array[$rowIndex]['user_salt'] = $salt;
			} else if ('E' == $cell -> getColumn()) {
				$array[$rowIndex]['email'] = $cell -> getCalculatedValue();
			} else if ('F' == $cell -> getColumn()) {
				$array[$rowIndex]['phone'] = $cell -> getCalculatedValue();
			} else if ('G' == $cell -> getColumn()) {
				$array[$rowIndex]['position'] = $cell -> getCalculatedValue();
			} else if ('H' == $cell -> getColumn()) {
				$array[$rowIndex]['department'] = $cell -> getCalculatedValue();
			} else if ('I' == $cell -> getColumn()) {
				$array[$rowIndex]['address'] = $cell -> getCalculatedValue();
			} else if ('J' == $cell -> getColumn()) {
				$array[$rowIndex]['user_role'] = $cell -> getCalculatedValue();
			} else if ('K' == $cell -> getColumn()) {
				$array[$rowIndex]['create_date'] = $cell -> getCalculatedValue();
			} else if ('L' == $cell -> getColumn()) {
				$array[$rowIndex]['delete_flag'] = $cell -> getCalculatedValue();
			} 
				}
				
	}

	// Data insert successful or not
	if (insertUsersBatch($array, $db)) {
	
	
		$_SESSION['cmd']['err']="success";
		header("location: ../admin/user_import.php");
	   
		exit ;
	} else {
	
		$_SESSION['cmd']['err']="error";
		header("location: ../admin/user_import.php");
		exit ;
	}
}

    ?>